language: cpp
compiler: gcc
- os: linux
      name: "Xenial - gcc 9"
      dist: xenial
      env: [USE_CC='/usr/bin/gcc-9', USE_CXX='/usr/bin/g++-9']
      addons:
        apt:
          packages: ['gcc-9', 'g++-9', 'cmake']
          sources: ['ubuntu-toolchain-r-test']

before_install:
  # Override compilers set by Travis
  - if [ ! -z "${USE_CC}" ]; then echo "Override CC=${USE_CC}"; eval "CC=${USE_CC}"; fi
  - if [ ! -z "${USE_CXX}" ]; then echo "Override CXX=${USE_CXX}"; eval "CXX=${USE_CXX}"; fi
  - echo ${CC} && ${CC} --version
  - echo ${CXX} && ${CXX} --version

install:
  # add SDL2 lib
  - wget https://www.libsdl.org/release/SDL2-2.0.10.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-* && ./configure && make && sudo make install && popd
  # this install step will take care of deploying a newer cmake version
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.16/cmake-3.16.0-rc2-Linux-x86_64.tar.gz
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.16.0-rc2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.16.0-rc2-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}

  # Install other dependencies
  - export PATH="$HOME/.cargo/bin:$PATH"
  - cmake .
  - make deps
  #-git fetch --unshallow


script:
 # - export CC=gcc-9
 # - export CXX=g++-9
  - cmake --version
  - gcc --version
  - BIN_DIR="${TRAVIS_BUILD_DIR}/bin"
  - mkdir ${BIN_DIR} && cd ${BIN_DIR}
  - echo $PWD
  - cmake ..
  - echo $PWD
  - cmake --build ..
  #- ctect .
